export interface VisualizerLessonProfile {
  slug: string;
  label: string;
  focus: string;
  input: string;
  output: string;
  code: string[];
  values?: number[];
}

const overrides: Record<string, Omit<VisualizerLessonProfile, 'slug' | 'label'>> = {
  'maximal-square': { focus: 'grow the largest all-ones square ending at the active cell', input: '4 x 5 binary matrix', output: 'largest square = 2', code: ['dp = zero_matrix(m + 1, n + 1)', 'for r, c in matrix:', '  dp[r][c] = 1 + min(up, left, diagonal)', '  best = max(best, dp[r][c])', 'return best * best'] },
  'lru-cache': { focus: 'keep recent nodes in a doubly linked list while the map gives O(1) lookup', input: 'capacity = 2; get(A), put(B)', output: 'least-recent node evicted', code: ['cache = {}; order = linked_list()', 'if key in cache: move_to_front(key)', 'else: insert_at_front(key)', 'while size > capacity: remove_tail()', 'return cache.get(key)'] },
  'generate-parentheses': { focus: 'only place a close parenthesis when it cannot make the prefix invalid', input: 'n = 3 pairs', output: '5 valid strings', code: ['search(open, close, path)', 'if open < n: choose "("', 'if close < open: choose ")"', '  recurse with updated counts', 'return completed paths'] },
  'flood-fill': { focus: 'spread the replacement color to each connected neighbor exactly once', input: 'start = (1, 1)', output: 'connected region recolored', code: ['queue = [start]', 'while queue:', '  cell = queue.pop()', '  add same-color neighbors', 'return image'] },
  'gas-station': { focus: 'reset the candidate start after the running tank becomes negative', input: 'gas - cost totals', output: 'start station = 3', code: ['total = 0; tank = 0; start = 0', 'for i in range(n):', '  total += gas[i] - cost[i]', '  if tank < 0: start = i + 1; tank = 0', 'return start if total >= 0 else -1'] },
  'single-number': { focus: 'cancel pairs with XOR so only the unpaired value remains', input: '[4, 1, 2, 1, 2]', output: 'single = 4', code: ['answer = 0', 'for value in nums:', '  answer = answer XOR value', '  paired bits cancel to zero', 'return answer'] },
  'reverse-bits': { focus: 'move the lowest bit into the mirrored position on every iteration', input: '00000010100101000001111010011100', output: '964176192', code: ['answer = 0', 'repeat 32 times:', '  answer = answer << 1 | (n & 1)', '  n = n >> 1', 'return answer'] },
  'path-sum-ii': { focus: 'carry the current root-to-leaf path and backtrack after each branch', input: 'target sum = 22', output: 'paths [[5,4,11,2], [5,8,4,5]]', code: ['dfs(node, remaining, path)', 'path.append(node.value)', 'if leaf and remaining == value: record path', 'dfs(left); dfs(right); path.pop()', 'return paths'] },
  'move-zeroes': { focus: 'compact non-zero values forward while preserving their relative order', input: '[0, 1, 0, 3, 12]', output: '[1, 3, 12, 0, 0]', code: ['write = 0', 'for read in range(n):', '  if nums[read] != 0:', '    swap(nums[write], nums[read]); write += 1', 'return nums'] },
  'missing-number': { focus: 'use the expected XOR cancellation to expose the missing index', input: '[3, 0, 1]', output: 'missing = 2', code: ['answer = n', 'for index, value in enumerate(nums):', '  answer = answer XOR index XOR value', '  matching values cancel', 'return answer'] },
  'palindrome-partitioning': { focus: 'cut only at substrings that read the same in both directions', input: '"aab"', output: '[["a","a","b"],["aa","b"]]', code: ['search(start, path)', 'for end from start to n:', '  if s[start:end] is palindrome:', '    choose substring and recurse', 'return partitions'] },
  'sum-of-two-integers': { focus: 'separate carry bits from sum bits until no carry remains', input: 'a = 5, b = 7', output: 'sum = 12', code: ['while b != 0:', '  carry = (a & b) << 1', '  a = a XOR b', '  b = carry', 'return a'] },
  'same-tree': { focus: 'compare matching nodes recursively, including null structure', input: 'trees P and Q', output: 'same structure and values', code: ['same(p, q):', 'if both null: return true', 'if one null or values differ: return false', 'return same(left) and same(right)', 'return same(rootP, rootQ)'] },
  'n-queens': { focus: 'place one queen per row while rejecting occupied columns and diagonals', input: 'n = 4', output: '2 valid boards', code: ['search(row)', 'if row == n: record board', 'for col in range(n):', '  if column and diagonals are free: place; recurse; undo', 'return boards'] },
  'contains-duplicate': { focus: 'let a set remember every value seen before the current scan position', input: '[1, 2, 3, 1]', output: 'duplicate = 1', code: ['seen = set()', 'for value in nums:', '  if value in seen: return true', '  seen.add(value)', 'return false'] },
  'group-anagrams': { focus: 'use a canonical character-count key to gather words with equal letter makeup', input: '[eat, tea, tan, ate, nat, bat]', output: '3 groups', code: ['groups = map()', 'for word in words:', '  key = frequency_signature(word)', '  groups[key].append(word)', 'return groups.values()'] },
  'split-array-largest-sum': { focus: 'binary search the smallest feasible maximum subarray sum', input: '[7,2,5,10,8], k = 2', output: 'minimum largest sum = 18', code: ['lo = max(nums); hi = sum(nums)', 'while lo < hi:', '  mid = (lo + hi) // 2', '  keep mid if it fits in k parts', 'return lo'] },
  'jump-game': { focus: 'track the furthest index reachable from the prefix already scanned', input: '[2,3,1,1,4]', output: 'last index reachable', code: ['reach = 0', 'for i, jump in enumerate(nums):', '  if i > reach: return false', '  reach = max(reach, i + jump)', 'return true'] },
  'course-schedule': { focus: 'remove zero-indegree courses to detect whether the prerequisite graph has a cycle', input: '2 courses, prerequisites [[1,0]]', output: 'can finish = true', code: ['build adjacency and indegree', 'queue = all zero-indegree nodes', 'while queue:', '  remove course; decrement neighbors', 'return processed == numCourses'] },
  'non-overlapping-intervals': { focus: 'keep the interval with the earliest finish so the next choice has room', input: '[[1,2],[2,3],[3,4],[1,3]]', output: 'remove = 1', code: ['sort intervals by end', 'keep_end = -infinity', 'for start, end in intervals:', '  keep if start >= keep_end; else remove', 'return removals'] },
  'valid-anagram': { focus: 'subtract matching character counts until every bucket returns to zero', input: 'anagram / nagaram', output: 'same frequency signature', code: ['count = frequency_map(s)', 'for char in t:', '  count[char] -= 1', '  reject if count[char] < 0', 'return all counts are zero'] },
  'swap-nodes-in-pairs': { focus: 'rewire two adjacent nodes at a time while preserving the untouched suffix', input: '1 -> 2 -> 3 -> 4', output: '2 -> 1 -> 4 -> 3', code: ['dummy.next = head', 'while first and first.next:', '  second = first.next', '  first.next, second.next = second.next, first', 'return dummy.next'] },
  'valid-palindrome': { focus: 'move inward while skipping punctuation and comparing normalized characters', input: '"A man, a plan, a canal: Panama"', output: 'palindrome = true', code: ['left = 0; right = n - 1', 'while left < right:', '  skip non-alphanumeric characters', '  compare lowercase characters; move inward', 'return true'] },
  'climbing-stairs': { focus: 'reuse the two previous stair counts to build the next total', input: 'n = 5', output: 'ways = 8', code: ['one = 1; two = 1', 'repeat n times:', '  one, two = two, one + two', '  advance one stair', 'return one'] },
  'edit-distance': { focus: 'choose insert, delete, or replace from the three neighboring edit states', input: 'horse -> ros', output: 'distance = 3', code: ['dp[0][c] = c; dp[r][0] = r', 'for each pair of characters:', '  if equal: use diagonal', '  else: 1 + min(insert, delete, replace)', 'return dp[m][n]'] },
  'course-schedule-ii': { focus: 'topologically order every course after its prerequisites become available', input: '4 courses', output: 'order [0,1,2,3]', code: ['build graph and indegrees', 'queue = zero-indegree courses', 'while queue:', '  append course; unlock neighbors', 'return order or []'] },
  'word-ladder': { focus: 'expand the smallest breadth-first frontier of one-letter transformations', input: 'hit -> cog', output: 'shortest length = 5', code: ['queue = [(begin, 1)]', 'while queue:', '  word, distance = queue.pop()', '  enqueue unseen one-letter neighbors', 'return distance when end is reached'] },
  'number-of-islands': { focus: 'sink one connected land component before moving to the next unvisited cell', input: '4 x 5 grid', output: 'islands = 1', code: ['count = 0', 'for each cell:', '  if land: count += 1; flood-fill it', 'mark all connected land as water', 'return count'] },
  'coin-change': { focus: 'build the fewest-coin answer from smaller amounts already solved', input: 'coins [1,2,5], amount = 11', output: 'minimum coins = 3', code: ['dp[0] = 0; others = infinity', 'for amount from 1 to target:', '  for coin in coins:', '    dp[amount] = min(dp[amount], 1 + dp[amount-coin])', 'return dp[target]'] },
  'longest-valid-parentheses': { focus: 'use unmatched opening indices as boundaries for the current valid span', input: '")()())"', output: 'longest length = 4', code: ['stack = [-1]', 'for index, char in enumerate(s):', '  push opening index', '  pop on close; reset boundary if empty', 'track index - stack[-1]'] },
  'decode-ways': { focus: 'count valid one-digit and two-digit decodings ending at each position', input: '"226"', output: 'decodings = 3', code: ['dp[0] = 1', 'for each position:', '  add dp[i-1] for valid one-digit code', '  add dp[i-2] for valid two-digit code', 'return dp[n]'] },
  'reorder-list': { focus: 'split, reverse, and weave the two halves into alternating nodes', input: '1 -> 2 -> 3 -> 4', output: '1 -> 4 -> 2 -> 3', code: ['find midpoint with slow and fast', 'reverse the second half', 'while right half exists:', '  weave left node, right node', 'return head'] },
  'find-k-closest-elements': { focus: 'shrink a sorted window from the side farther from x until k remain', input: 'arr [1,2,3,4,5], x = 3, k = 4', output: '[1,2,3,4]', code: ['left = 0; right = n - k', 'while left < right:', '  mid = (left + right) // 2', '  move toward the closer window', 'return arr[left:left+k]'] },
  'merge-k-sorted-lists': { focus: 'use the heap to always link the smallest current list head', input: '3 sorted linked lists', output: 'one sorted list', code: ['push each non-null head into heap', 'while heap:', '  node = pop smallest', '  append node to result', '  push node.next'] },
  'daily-temperatures': { focus: 'a decreasing stack stores temperatures waiting for a warmer day', input: '[73,74,75,71,69,72,76,73]', output: '[1,1,4,2,1,1,0,0]', code: ['stack = []', 'for day, temperature in enumerate(temps):', '  while stack and temperature > stack.top:', '    resolve waiting day', '  push day'] },
  'valid-triangle-number': { focus: 'for a fixed largest side, move two pointers while the triangle inequality holds', input: '[2,2,3,4]', output: 'triangles = 3', code: ['sort nums', 'for right from n - 1 down:', '  left = 0; mid = right - 1', '  count all pairs with nums[left] + nums[mid] > nums[right]', 'return count'] },
  'subarray-sum-equals-k': { focus: 'a prefix-sum frequency map turns each target range into a lookup', input: '[1,1,1], k = 2', output: 'subarrays = 2', code: ['seen = {0: 1}; prefix = 0', 'for value in nums:', '  prefix += value', '  answer += seen[prefix - k]; seen[prefix] += 1', 'return answer'] },
  'surrounded-regions': { focus: 'protect border-connected O cells, then flip only the truly enclosed region', input: '4 x 4 board', output: 'enclosed O cells flipped', code: ['start flood-fill from every border O', 'mark safe cells with sentinel', 'flip remaining O to X', 'restore sentinel to O', 'return board'] },
  'combination-sum': { focus: 'keep a nondecreasing candidate index so duplicate orderings never repeat', input: 'candidates [2,3,6,7], target = 7', output: '[[2,2,3],[7]]', code: ['search(start, remaining, path)', 'if remaining == 0: record path', 'for i from start while candidate <= remaining:', '  choose candidate; recurse; undo', 'return combinations'] },
  'jump-game-ii': { focus: 'finish the current jump layer before committing to the furthest next reach', input: '[2,3,1,1,4]', output: 'minimum jumps = 2', code: ['jumps = 0; current_end = 0; farthest = 0', 'for i before last index:', '  farthest = max(farthest, i + nums[i])', '  if i == current_end: jumps += 1; current_end = farthest', 'return jumps'] },
  'min-stack': { focus: 'store the minimum alongside each stack state so getMin stays constant time', input: 'push -2, 0, -3', output: 'getMin() = -3', code: ['values = []; minimums = []', 'push value and min(value, current min)', 'pop both stacks together', 'top reads values[-1]', 'getMin reads minimums[-1]'] },
  'subsets': { focus: 'branch once for excluding and once for including each value', input: '[1,2,3]', output: '8 subsets', code: ['search(index, path)', 'if index == n: record path', 'search(index + 1, path)', 'search(index + 1, path + [nums[index]])', 'return subsets'] },
  'container-with-most-water': { focus: 'move the shorter wall because the taller wall cannot improve the current height', input: '[1,8,6,2,5,4,8,3,7]', output: 'max area = 49', code: ['left = 0; right = n - 1', 'area = min(height[left], height[right]) * width', 'record maximum area', 'move the shorter pointer inward', 'return maximum'] },
  'number-of-1-bits': { focus: 'remove the lowest set bit repeatedly until the integer becomes zero', input: '00000000000000000000000000001011', output: 'set bits = 3', code: ['count = 0', 'while n != 0:', '  n = n & (n - 1)', '  count += 1', 'return count'] },
  'rotate-image': { focus: 'transpose the square then reverse each row to rotate in place', input: '3 x 3 matrix', output: 'rotated clockwise', code: ['transpose across the diagonal', 'for each row:', '  reverse(row)', 'each cell moves once', 'return matrix'] },
  'add-two-numbers': { focus: 'walk both lists while carrying overflow into the next digit', input: '342 + 465', output: '807', code: ['carry = 0; node = dummy', 'while l or r or carry:', '  total = l.val + r.val + carry', '  append total % 10; carry = total // 10', 'return dummy.next'] },
  'merge-intervals': { focus: 'sort by start and extend the active interval while overlaps continue', input: '[[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]', code: ['sort intervals by start', 'current = first interval', 'for next in intervals:', '  merge if next.start <= current.end', 'return merged'] },
  'merge-two-sorted-lists': { focus: 'link the smaller head and advance only that list', input: '1->2->4 and 1->3->4', output: '1->1->2->3->4->4', code: ['dummy = node(0); tail = dummy', 'while left and right:', '  link smaller node to tail', 'advance chosen node and tail', 'append remaining suffix'] },
  'trapping-rain-water': { focus: 'the lower boundary determines how much water the current pointer can hold', input: '[0,1,0,2,1,0,1,3,2,1,2,1]', output: 'trapped water = 6', code: ['left = 0; right = n - 1', 'track leftMax and rightMax', 'move the side with lower boundary', 'add boundary - height when positive', 'return water'] },
  'linked-list-cycle': { focus: 'a fast pointer laps a slow pointer exactly when a cycle exists', input: '3 -> 2 -> 0 -> -4 -> 2', output: 'cycle entry = 2', code: ['slow = head; fast = head', 'while fast and fast.next:', '  slow = slow.next; fast = fast.next.next', 'if slow == fast: cycle found', 'return false'] },
  'redundant-connection': { focus: 'union-find identifies the edge whose endpoints already share a component', input: 'edges [[1,2],[1,3],[2,3]]', output: 'redundant edge = [2,3]', code: ['parent = range(n + 1)', 'for u, v in edges:', '  if find(u) == find(v): return [u, v]', '  union(u, v)', 'return []'] },
  'two-sum': { focus: 'store each complement so the answer is found in one forward pass', input: '[2,7,11,15], target = 9', output: 'indices [0,1]', code: ['seen = {}', 'for i, value in enumerate(nums):', '  need = target - value', '  if need in seen: return [seen[need], i]', '  seen[value] = i'] },
  'permutation-in-string': { focus: 'slide a fixed-size frequency window until it matches the target signature', input: 's1 = ab, s2 = eidbaooo', output: 'permutation found', code: ['need = frequency(s1); window = frequency(first k)', 'for right in range(k, len(s2)):', '  add s2[right]; remove leftmost', '  compare frequency signatures', 'return match'] },
  'word-search': { focus: 'walk adjacent cells while marking the current path and undoing on backtrack', input: 'board contains "ABCCED"', output: 'word found = true', code: ['search(r, c, index)', 'reject bounds, mismatch, or visited cell', 'mark cell; search four neighbors', 'unmark cell before returning', 'return found'] },
  'set-matrix-zeroes': { focus: 'use the first row and column as in-place marker storage', input: '3 x 3 matrix with zeroes', output: 'marked rows and columns zeroed', code: ['record whether first row/column contain zero', 'mark row and column headers', 'zero marked interior cells', 'restore first row and column', 'return matrix'] },
  'valid-parentheses': { focus: 'the top of the stack must match each closing bracket', input: '"()[]{}"', output: 'valid = true', code: ['stack = []', 'for bracket in s:', '  push expected closer for opening bracket', '  reject if close != stack.pop()', 'return stack is empty'] },
  'sliding-window-maximum': { focus: 'a decreasing deque keeps the maximum of the current window at its front', input: '[1,3,-1,-3,5,3,6,7], k = 3', output: '[3,3,5,5,6,7]', code: ['deque = []; answer = []', 'for right, value in enumerate(nums):', '  remove smaller values from back', '  remove indices outside window', '  append deque.front after window opens', 'return answer'] },
  'longest-univalue-path': { focus: 'combine equal downward branches at each node and keep the best global path', input: 'binary tree values', output: 'longest same-value path = 2', code: ['dfs(node):', 'left = dfs(node.left); right = dfs(node.right)', 'extend equal child branches', 'answer = max(answer, left + right)', 'return longest one-sided branch'] },
  'counting-bits': { focus: 'the highest set bit points to a previously solved offset', input: 'n = 5', output: '[0,1,1,2,1,2]', code: ['dp[0] = 0; offset = 1', 'for value from 1 to n:', '  if value == offset << 1: offset <<= 1', '  dp[value] = 1 + dp[value - offset]', 'return dp'] },
  'spiral-matrix': { focus: 'shrink the four boundaries after completing each side of the spiral', input: '3 x 3 matrix', output: 'spiral order = [1,2,3,6,9,8,7,4,5]', code: ['top, bottom, left, right = bounds', 'walk top row and increment top', 'walk right column and decrement right', 'walk bottom and left when bounds remain', 'return order'] },
  'path-sum': { focus: 'subtract each node from the remaining target until a leaf closes the path', input: 'target sum = 22', output: 'path exists = true', code: ['dfs(node, remaining):', 'if node is null: return false', 'remaining -= node.value', 'at leaf, check remaining == 0', 'return dfs(left) or dfs(right)'] },
  '01-matrix': { focus: 'multi-source breadth-first search expands distance rings from every zero', input: 'matrix with zero and one cells', output: 'distance to nearest zero', code: ['queue = every zero cell', 'mark zero cells as distance 0', 'while queue:', '  visit four neighbors once', 'distance[neighbor] = distance[current] + 1'] },
  'house-robber': { focus: 'at each house choose between robbing it plus two-back or skipping it', input: '[2,7,9,3,1]', output: 'maximum loot = 12', code: ['prev2 = 0; prev1 = 0', 'for money in nums:', '  current = max(prev1, prev2 + money)', '  prev2, prev1 = prev1, current', 'return prev1'] },
  'insert-interval': { focus: 'merge the new interval across every overlapping run in one ordered scan', input: '[[1,3],[6,9]], new [2,5]', output: '[[1,5],[6,9]]', code: ['append intervals ending before new.start', 'merge every overlapping interval', 'append merged interval', 'append remaining intervals', 'return result'] },
  'network-delay-time': { focus: 'Dijkstra finalizes the next closest signal and relaxes its outgoing edges', input: 'directed weighted graph', output: 'all nodes reached in 2 time', code: ['distance[source] = 0; heap = [(0, source)]', 'while heap:', '  time, node = pop smallest', '  relax every outgoing edge', 'return max distance or -1'] },
  'sort-colors': { focus: 'the Dutch national flag boundaries keep red, white, and blue regions separated', input: '[2,0,2,1,1,0]', output: '[0,0,1,1,2,2]', code: ['low = 0; mid = 0; high = n - 1', 'while mid <= high:', '  swap 0 to low; swap 2 to high', '  advance the matching boundary', 'return nums'] },
  'task-scheduler': { focus: 'schedule the most frequent tasks first and count the idle gaps they create', input: '[A,A,A,B,B,B], cooldown = 2', output: 'least intervals = 8', code: ['count task frequencies', 'place most frequent task in cooldown slots', 'fill gaps with other tasks', 'idle only when no task fits', 'return max(work, frame lower bound)'] },
  'unique-paths': { focus: 'each grid cell inherits the number of ways from its top and left neighbors', input: 'm = 3, n = 7', output: 'ways = 28', code: ['dp = [1] * n', 'for each remaining row:', '  for col from 1 to n:', '    dp[col] += dp[col - 1]', 'return dp[n - 1]'] },
  'reverse-linked-list': { focus: 'save next, reverse current.next, then advance the two pointers', input: '1 -> 2 -> 3 -> 4 -> 5', output: '5 -> 4 -> 3 -> 2 -> 1', code: ['prev = null; current = head', 'while current:', '  next = current.next', '  current.next = prev', '  prev = current; current = next'] },
  'permutations': { focus: 'swap each remaining choice into the next position, then undo the swap', input: '[1,2,3]', output: '6 permutations', code: ['search(index)', 'if index == n: record nums', 'for i from index to n:', '  swap(index, i); search(index + 1)', '  swap(index, i)'] },
  'binary-search': { focus: 'discard half the sorted search interval after every midpoint comparison', input: '[-1,0,3,5,9,12], target = 9', output: 'index = 4', code: ['left = 0; right = n - 1', 'while left <= right:', '  mid = (left + right) // 2', '  move left or right past mid', 'return index or -1'] },
  'longest-increasing-subsequence': { focus: 'maintain the smallest possible tail for every subsequence length', input: '[10,9,2,5,3,7,101,18]', output: 'LIS length = 4', code: ['tails = []', 'for value in nums:', '  position = lower_bound(tails, value)', '  replace tail at position', 'return len(tails)'] },
  'decode-string': { focus: 'nested stacks restore the previous prefix and repeat count at each closing bracket', input: '"3[a2[c]]"', output: '"accaccacc"', code: ['counts = []; prefixes = []; current = ""', 'read repeat count', 'push count and current prefix on [', 'on ]: current = prefix + count * current', 'return current'] },
  'palindrome-linked-list': { focus: 'reverse the second half and compare it with the first half node by node', input: '1 -> 2 -> 2 -> 1', output: 'palindrome = true', code: ['find midpoint with slow and fast', 'reverse second half', 'compare left and right halves', 'restore links if desired', 'return equal'] },
  'word-break': { focus: 'mark a prefix reachable when its suffix is a dictionary word', input: '"leetcode", [leet, code]', output: 'can segment = true', code: ['dp[0] = true', 'for end from 1 to n:', '  for start before end:', '    dp[end] |= dp[start] and s[start:end] in dictionary', 'return dp[n]'] },
};

function prettify(slug: string) {
  return slug.split('-').map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}

function stableValues(slug: string) {
  let hash = 0;
  for (const char of slug) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return Array.from({ length: 7 }, (_, index) => 3 + ((hash >>> (index * 3)) % 28));
}

export function getVisualizerLesson(pathOrTitle: string, pattern: string): VisualizerLessonProfile {
  const slug = pathOrTitle.split('/').filter(Boolean).pop()?.toLowerCase() || 'algorithm';
  const custom = overrides[slug];
  if (custom) return { slug, label: prettify(slug), ...custom, values: custom.values || stableValues(slug) };
  return {
    slug,
    label: prettify(slug),
    focus: `apply ${prettify(slug)} while preserving the ${pattern} invariant`,
    input: `${prettify(slug)} sample input`,
    output: `${prettify(slug)} answer resolved`,
    code: [`state = initial_${slug.replaceAll('-', '_')}()`, 'for each active state:', '  inspect the next candidate', '  update the invariant and continue', 'return the resolved answer'],
    values: stableValues(slug),
  };
}

export function hasCustomVisualizerLesson(pathOrTitle: string) {
  const slug = pathOrTitle.split('/').filter(Boolean).pop()?.toLowerCase() || 'algorithm';
  return Boolean(overrides[slug]);
}
